//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOD_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Margin
    {
        public int ProductID { get; set; }
        public decimal UnitCost { get; set; }
        public decimal UnitSell { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
